# Generated by Django 3.2.2 on 2021-05-10 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('about_me', models.CharField(max_length=510)),
                ('created_at', models.DateField(verbose_name='date created')),
                ('upated_at', models.DateField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('about_project', models.CharField(max_length=500)),
                ('pesonal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.personaldata')),
            ],
        ),
    ]
