# Generated by Django 3.2.2 on 2021-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='about_project',
            field=models.TextField(),
        ),
    ]
